### PR TITLE
Adjustments to linalg in influence calculation

### PR DESCRIPTION
**Pull request by nk027**
I've been thinking about influence calculations for IV and adapted some straightforward stuff in your code:
- One QR of Z (get Z'Z⁻¹ directly, and robust solving for pi, see point 3 below),
- Use Cholesky inverse for symmetric matrices,
- Use `tcrossprod(a, b)` instead of `a %*% t(b)`.

I noticed some weird stuff that may be intentional:
1) `r` is just a left projected `X`, i.e. `t(X.fit)`,
2) `.sigma <- sqrt(model$sigma^2)` for an absolute (?),
3) Calculation with `Ainv` and the like would be cleaner / more stable using the factorised matrix instead.

I may benchmark some approaches to getting influence quantities and get back to the code if you want. Have you tried different approaches or are you sticking to Phillips' equations?

Best,

### CODE REVIEW

**Comment by john-d-fox** [comment]
Dear Nicholas,

On 2021-07-01 5:51 a.m., Nikolas Kuschnig wrote:
> I've been thinking about influence calculations for IV and adapted some 
> straightforward stuff in your code:
> 
>   * One QR of Z (get Z'Z⁻¹ directly, and robust solving for pi, see
>     point 3 below),
>   * Use Cholesky inverse for symmetric matrices,
>   * Use |tcrossprod(a, b)| instead of |a %*% t(b)|.
> 
> I noticed some weird stuff that may be intentional:
> 
>  1. |r| is just a left projected |X|, i.e. |t(X.fit)|,
>  2. |.sigma <- sqrt(model$sigma^2)| for an absolute (?),
>  3. Calculation with |Ainv| and the like would be cleaner / more stable
>     using the factorised matrix instead.
> 
> I may benchmark some approaches to getting influence quantities and get 
> back to the code if you want. Have you tried different approaches or are 
> you sticking to Phillips' equations?

Phillips's results are sufficiently complicated that I concentrated on 
programming them straightforwardly. In the process, I discovered small 
errors in his formulas, which I corrected.

First, your suggestions for improving the computations seem reasonable 
to me, and they might both speed up the computations and make them more 
numerically stable. So please do go ahead and see whether your changes 
make a difference. The automated package checks should protect against 
introducing errors.

Second, .sigma <- sqrt(model$sigma^2) is just carelessness, possibly 
inherited from earlier code in which sigma^2 rather than sigma was 
stored, and I've now fixed that in the package sources on GitHub.

Thaks for this,
  John

**Comment by nk027** [comment]
Dear John @john-d-fox,

I adjusted the code accordingly and took the liberty of adding myself as one of the authors (commit a78dbedbc73a3de92d9bf402f9be3531a966c708). I described the changes in the commit message, but in short --- the code now builds more heavily on factorisations. Quantities are reused where possible and no explicit inverses are formed.

As a result, the code should run quite a bit faster now, especially when `sigma` is computed as well. Here are some benchmarks:

- cigarettes dataset: 4.9 (old) vs 3.2 ms (new)
- N = 1000, K = 2 * 2: 135 vs 95 ms
- N = 1000, K = 2 * 10: 432 vs 182 ms
- N = 5000, K = 2 * 10: 9,824 vs 2,782 ms
- N = 5000, K = 2 * 10, no-sigma: 337 vs 329 ms
- N = 5000, K = 2 * 20: 15,143 vs 4,847 ms
- N = 5000, K = 2 * 20, no-sigma: 414 vs 406 ms

Regarding accuracy the results usually differ at a magnitude of about 1e-12. Errors (i.e. differences to actual results of removing an observation) are of a similar magnitude. Theoretically, the new code should be more stable numerically (QR instead of LU, solves systems instead of explicit inversion), but I was not able to test this empirically. I stumbled upon some pathologically ill-conditioned problems, where both algorithms may be off by a lot.
If it's relevant or you are interested I can share my script for these benchmarks.

I did not bother `R CMD` checking the package, but the unit tests in `test-case-deletion.R` run through. I hope my changes are  of some use.

Best,
Nikolas

**Comment by nk027** [comment]
I noticed that the scaling in *N* was off a bit and profiled a bit more. This was due to `dffits` being computed using the whole matrix. I also changed this to use `vapply()` instead, leading to much better scaling. Now the speed increase does not drop off in *N*. Here is an additional benchmark (mean times):

- N = 25000, K = 2 * 10: 1080 (old) vs 533 ms (new)

**Comment by john-d-fox** [comment]
Dear Nikolas,

Thanks for this and for your other messages and improvements. For the 
larger problems, you're showing a more than three-fold increase in 
speed, which seems worthwhile to me.

I'll take a look at what you did as soon as I have a chance.

With respect to listing yourself as an "author" of the package, as I 
understand the norms for crediting contributions to R packages, this 
sort of contribution would normally be acknowledged by listing you as a 
"contributor" to the package. I hope that you don't find that offensive.

Best,
  John

John Fox, Professor Emeritus
McMaster University
Hamilton, Ontario, Canada
web: https://socialsciences.mcmaster.ca/jfox/

**Comment by nk027** [comment]
Dear John,

No problem, I've been working on this anyway and the PR was a good way to gain some closer insights. With respect to `ctb` that's absolutely fine and I fixed it. I just messed up the roles in my head and did not mean to take excessive credit. [Here's](https://github.com/john-d-fox/ivreg/files/6772925/test_ivreg.txt)'s readable parts of a script I used to test the changes.

Best,

**Comment by john-d-fox** [comment]
Dear Nikolas,

I'm glad that you weren't offended by my suggestion of the contributor 
role, at least for the present.

I took a quick look at your code and I noticed that in a couple of 
places -- e.g., in the computation of studenized residuals -- you 
removed multiplication by the weights. I would have thought that should 
produce an error in the package tests, which among other things check 
that studenized residuals are computed correctly with weights, but from 
your description, the tests run without error. You must have 
accommodated the weights in a way that I didn't immediately see. Is that 
right?

Thanks again for this,
  John

**Comment by nk027** [comment]
Hey John,

That's correct, the weights are added to the residuals around line 150 with the other objects. Since two additional types of residuals are needed for `g`, all exclusively in weighted form, and the main `res` is needed with weights multiple times I figured it was cleaner to do this in one go.  If line 158 is removed and instances of `res` below are replaced with `res * w` the process is earlier one again.

**Comment by john-d-fox** [comment]
Dear Nikolas,

After reviewing your code some more and running some tests, I've merged 
your changes with the main branch of ivreg on GitHub.

Thank you very much for your contribution,
  John

**Pull request merged**
